### ISSUE TITLE
bug: Alpine apk extractor does not correctly extract commit hash

### ISSUE THREAD

**Issue by another-rex** [google/osv-scalibr#240]
The commit extractor is not extracting the correct commit line from the status file:
https://github.com/google/osv-scalibr/blob/c36dd4d152236eb1ba726f84cbc1b475ca0abf90/extractor/filesystem/os/apk/extractor.go#L169

It is trying to get the lines that starts with `c:<commit-hash>`, but instead I think it case-insensitively matched to the `C:` line instead, which is the file checksum.

**Comment by erikvarga** [comment]
With https://github.com/google/osv-scalibr/pull/241 has this been resolved?

**Comment by another-rex** [comment]
Yes, closing this now.
