### ISSUE TITLE
SPDX - "main" package does not have a SUPPLIER field

### ISSUE THREAD

**Issue by Martiul** [google/osv-scalibr#254]
I've used scalibr on a few images and jar files, but noticed that the top level `main` package does not have a `supplier` field, despite every other package having it

Is this intended, or is it a bug? 

Steps to reproduce:

Run `scalibr -o spdx23-json=...` (scanning anything should suffice)

**Comment by erikvarga** [comment]
Ah I think we just forgot to set it for the `main` package, there's no particular reason for why it shouldn't be set there. I'll send a PR to fix, thanks for catching!

**Comment by erikvarga** [comment]
Done in https://github.com/google/osv-scalibr/pull/255
